name: Hola mundo workflow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Paso hola mundo
      run: echo "Hola mundo desde github actions" 

    - name: Debug
      run: |
        echo "Debbuging: GITHUB_REF ${{ github.ref }}"
        echo "Debbuging: RUNNER_OS ${{ runner.os }}"

